<a href="https://colab.research.google.com/github/shrishtinigam/tensorflow-ztm/blob/main/00_TensorFlow_Tut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### https://github.com/mrdbourke/tensorflow-deep-learning/blob/main/00_tensorflow_fundamentals.ipynb

In [1]:
# Import TensorFlow
import tensorflow as tf

print(tf.__version__)

2.13.0


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Number of dimensions
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
# Create a matrix
matrix = tf.constant([[5, 9],[9, 5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 9],
       [9, 5]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[10.2, 4.2, 9.2],[3.6,3.3,2.0],[3.4,4.3,8.5]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[10.2,  4.2,  9.2],
       [ 3.6,  3.3,  2. ],
       [ 3.4,  4.3,  8.5]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# Create a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

Tensor: An n-dim array of numbers

Creating tensors with tf.Variable

In [12]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
#changeable_tensor[0] = 7

In [15]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [17]:
#unchangeable_tensor[0] = 7

In [19]:
#unchangeable_tensor[0].assign(7)

### Creating random tensors
Arbitary size, containing random numbers

In [21]:
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [22]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [23]:
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Shuffling the order of tensors

In [24]:
not_shuffled = tf.constant([[10, 7],[3, 4],[2, 5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

It's due to rule #4 of the tf.random.set_seed() documentation.

"4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

In [25]:
tf.random.set_seed(62)
tf.random.shuffle(not_shuffled, seed=62) # randomly shuffles along first dimension

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

https://www.tensorflow.org/api_docs/python/tf/random/set_seed

Other ways to make tensors

In [26]:
tf.ones([3,2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [27]:
tf.zeros(shape=(2,8))

<tf.Tensor: shape=(2, 8), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

Create NumPy arrays into tf tensors

In [28]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [29]:
a = tf.constant(numpy_A)
b = tf.constant(numpy_A, shape=(2, 3, 4))

In [30]:
a, b

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

Getting information from tensors
* shape - tensor.shape
* rank - tensor.ndim
* axis/dimension - tensor[0], tensor[:,1]. ..
* size - tf.size(tensor)


In [31]:
# Create a rank 4 tensor

rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [33]:
rank_4_tensor.shape, rank_4_tensor.ndim

(TensorShape([2, 3, 4, 5]), 4)

In [34]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [35]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor))
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): tf.Tensor(120, shape=(), dtype=int32)
Total number of elements (2*3*4*5): 120


Indexing and Expanding

In [36]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

Rank 4 tensor A

In [37]:
numpy_A = np.arange(0, 120, dtype=np.int32)
numpy_A

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119], dtype=int32)

In [38]:
A = tf.constant(numpy_A, shape=(2, 3, 4, 5))

In [39]:
A

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]], dtype=int32)>

In [40]:
# Get first two elements of each dimension
A[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[ 0,  1],
         [ 5,  6]],

        [[20, 21],
         [25, 26]]],


       [[[60, 61],
         [65, 66]],

        [[80, 81],
         [85, 86]]]], dtype=int32)>

In [41]:
# Get the first element from each dimension from each index except for the final one
A[:1, :1, :1]
A[:1, :1, :1].numpy()

array([[[[0, 1, 2, 3, 4]]]], dtype=int32)

In [42]:
A[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=int32, numpy=
array([[[[ 0],
         [ 5],
         [10],
         [15]]]], dtype=int32)>

Rank 2 tensor B

In [43]:
numpy_B = np.arange(0, 6, dtype=np.int32)
B = tf.constant(numpy_B, shape=(2, 3))

In [44]:
B

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]], dtype=int32)>

In [45]:
B.shape, B.ndim

(TensorShape([2, 3]), 2)

In [46]:
# Get the last item of each row of our rank 2 tensor
B[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5], dtype=int32)>

Add an extra dimension to the rank 2 tensor - Rank 3 tensor C

In [47]:
C = B[..., tf.newaxis] # same as -> C = B[:, :, tf.newaxis]
C

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]], dtype=int32)>

In [48]:
tf.expand_dims(B, axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]], dtype=int32)>

In [49]:
tf.expand_dims(B, axis=0) # expand the 0 axis

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[0, 1, 2],
        [3, 4, 5]]], dtype=int32)>

### Basic Tensor Operations

In [50]:
tensor_1 = tf.constant([[20, 6],[3, 5]])
tensor_1 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 16],
       [13, 15]], dtype=int32)>

In [51]:
tensor_1 * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200,  60],
       [ 30,  50]], dtype=int32)>

In [52]:
tensor_1 - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, -4],
       [-7, -5]], dtype=int32)>

We can use tf inbuilt functions so that the operation can be sped up on a GPU

In [53]:
tf.multiply(tensor_1, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200,  60],
       [ 30,  50]], dtype=int32)>

In [54]:
tf.add(tensor_1, 4)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[24, 10],
       [ 7,  9]], dtype=int32)>

### Matrix Multiplication
It is one the most common operations

In [55]:
x = tf.constant([[2, 5],[3, 7]])
y = tf.constant([[7, 6, 9],[1, 5, 8]])
tf.matmul(x, y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[19, 37, 58],
       [28, 53, 83]], dtype=int32)>

In [56]:
tf.matmul(x, x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 45],
       [27, 64]], dtype=int32)>

In [57]:
x * x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4, 25],
       [ 9, 49]], dtype=int32)>

In [58]:
x @ y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[19, 37, 58],
       [28, 53, 83]], dtype=int32)>

## Transpose vs Reshape
Transpose flips the axes whereas reshape maintains order of row-wise occurance

In [59]:
tf.reshape(y, shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[7, 6],
       [9, 1],
       [5, 8]], dtype=int32)>

In [60]:
tf.transpose(y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[7, 1],
       [6, 5],
       [9, 8]], dtype=int32)>

## The dot product
Multiplying matrices by each other is also referred to as the dot product.

You can perform the tf.matmul() operation using tf.tensordot().

In [61]:
x, y

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 5],
        [3, 7]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[7, 6, 9],
        [1, 5, 8]], dtype=int32)>)

In [62]:
tf.tensordot(tf.transpose(x), y, axes=1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 17,  27,  42],
       [ 42,  65, 101]], dtype=int32)>

In [63]:
# Create (3, 2) tensor
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

In [64]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [65]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(x, tf.reshape(y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [66]:
# Check values of Y, reshape Y and tranposed Y
print("Normal Y:")
print(y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


As you can see, the outputs of tf.reshape() and tf.transpose() when called on Y, even though they have the same shape, are different.

This can be explained by the default behaviour of each method:

tf.reshape() - change the shape of the given tensor (first) and then insert values in order they appear (in our case, 7, 8, 9, 10, 11, 12).
tf.transpose() - swap the order of the axes, by default the last axis becomes the first, however the order can be changed using the perm parameter.
So which should you use?

Again, most of the time these operations (when they need to be run, such as during the training a neural network, will be implemented for you).

### **But generally, whenever performing a matrix multiplication and the shapes of two matrices don't line up, you will transpose (not reshape) one of them in order to line them up.**

### Change the datatype of a tensor

In [67]:
B = tf.constant([1.7, 1.4])
B.dtype

tf.float32

In [68]:
B = tf.constant([1, 4])
B.dtype

tf.int32

In [69]:
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 4.], dtype=float16)>,
 tf.float16)

### Aggregating Tensors

In [70]:
B = tf.constant([[-1, -4],[-3, -7]])
B.dtype

tf.int32

In [71]:
tf.abs(B)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 4],
       [3, 7]], dtype=int32)>

* Minimum
* Maximum
* Mean
* Sum

In [72]:
E = tf.constant(np.random.randint(0, 100, size=50))
#E = tf.reshape(E, shape=(5, 5, 2))

In [73]:
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([39, 38, 60, 48, 74, 91, 13, 36, 23, 59, 60, 40, 29, 41, 15, 26, 13,
       71, 65, 84, 87, 50, 43, 19, 56, 92, 89, 10, 10, 48, 36, 55, 86, 31,
       34, 88, 56, 39, 67, 99, 71, 20, 96, 10, 44,  2, 63, 97, 61, 55])>

In [74]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [75]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [76]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [77]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2539>

* Variation
* Std Deviation

In [78]:
E = tf.cast(E, dtype=tf.float32)

In [79]:
tf.math.reduce_variance(E) # only works with floats ig

<tf.Tensor: shape=(), dtype=float32, numpy=718.6916>

In [80]:
tf.math.reduce_std(E) # only works with floats ig

<tf.Tensor: shape=(), dtype=float32, numpy=26.808424>

or using tfp

In [81]:
import tensorflow_probability as tfp

In [82]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=718.6916>

In [83]:
E.shape

TensorShape([50])

In [84]:
E

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([39., 38., 60., 48., 74., 91., 13., 36., 23., 59., 60., 40., 29.,
       41., 15., 26., 13., 71., 65., 84., 87., 50., 43., 19., 56., 92.,
       89., 10., 10., 48., 36., 55., 86., 31., 34., 88., 56., 39., 67.,
       99., 71., 20., 96., 10., 44.,  2., 63., 97., 61., 55.],
      dtype=float32)>

Positions of Max and Min

In [85]:
E = tf.constant(np.random.uniform(size=[36]))
# E = tf.reshape(E, shape=(12, 3))
E

<tf.Tensor: shape=(36,), dtype=float64, numpy=
array([0.6673897 , 0.66133204, 0.23984214, 0.26532368, 0.67640182,
       0.13153749, 0.17386232, 0.34342843, 0.43164923, 0.28445189,
       0.61290877, 0.29174499, 0.71762442, 0.51023232, 0.9510543 ,
       0.88982195, 0.94047628, 0.32767316, 0.93318382, 0.90101958,
       0.27170425, 0.56017063, 0.03278688, 0.55843498, 0.63276026,
       0.39006783, 0.15570127, 0.53125052, 0.16708906, 0.07309876,
       0.68041083, 0.78456422, 0.49494347, 0.01788687, 0.83270054,
       0.00291875])>

In [86]:
tf.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=14>

In [87]:
assert E[tf.argmax(E)] == tf.reduce_max(E)

In [88]:
# tf.argmax(E, axis = 1)

In [89]:
tf.argmin(E)

<tf.Tensor: shape=(), dtype=int64, numpy=35>

In [90]:
#tf.argmin(E, axis = 1)

In [91]:
E

<tf.Tensor: shape=(36,), dtype=float64, numpy=
array([0.6673897 , 0.66133204, 0.23984214, 0.26532368, 0.67640182,
       0.13153749, 0.17386232, 0.34342843, 0.43164923, 0.28445189,
       0.61290877, 0.29174499, 0.71762442, 0.51023232, 0.9510543 ,
       0.88982195, 0.94047628, 0.32767316, 0.93318382, 0.90101958,
       0.27170425, 0.56017063, 0.03278688, 0.55843498, 0.63276026,
       0.39006783, 0.15570127, 0.53125052, 0.16708906, 0.07309876,
       0.68041083, 0.78456422, 0.49494347, 0.01788687, 0.83270054,
       0.00291875])>

In [92]:
#E[tf.argmin(E, axis = 1)[0]]

## Squeezing a tensor (removing all dimensions of size 1)

In [93]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [94]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [95]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

## One Hot Encoding Tensors

In [96]:
# Creat a list of indices
some_list = [0, 1, 2, 3, 3, 2, 1]
#depth = 5

# One hot encode list of indices
tf.one_hot(some_list, depth=5)

<tf.Tensor: shape=(7, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.]], dtype=float32)>

In [97]:
tf.one_hot(some_list, depth=5, on_value="On Value", off_value="Off Value")

<tf.Tensor: shape=(7, 5), dtype=string, numpy=
array([[b'On Value', b'Off Value', b'Off Value', b'Off Value',
        b'Off Value'],
       [b'Off Value', b'On Value', b'Off Value', b'Off Value',
        b'Off Value'],
       [b'Off Value', b'Off Value', b'On Value', b'Off Value',
        b'Off Value'],
       [b'Off Value', b'Off Value', b'Off Value', b'On Value',
        b'Off Value'],
       [b'Off Value', b'Off Value', b'Off Value', b'On Value',
        b'Off Value'],
       [b'Off Value', b'Off Value', b'On Value', b'Off Value',
        b'Off Value'],
       [b'Off Value', b'On Value', b'Off Value', b'Off Value',
        b'Off Value']], dtype=object)>

## Math operations
Squaring
Log
Square Root

In [98]:
# Create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [99]:
# Squaring it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [101]:
# Square Root - ERROR - Method requires non-int type
#tf.sqrt(H)

In [102]:
# Square Root
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [103]:
# Log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Tensors and Numpy
TensorFlow interacts beautifully with numpy arrays.


In [104]:
# Create a tensor directly from a Numpy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [105]:
# Convert tensor J to a Numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [106]:
# Convert Tensor J to a numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [107]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [108]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## Access GPUs

In [109]:
tf.config.list_physical_devices("GPU")

[]

In [110]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [111]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


If you have a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible.

## 00. TensorFlow Fundamentals Exercises



Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().


In [112]:
s = tf.constant(9)
v = tf.constant([3,4,5])
m = tf.constant([[3,4,9],[10,34,2]])
t = tf.constant([[[2,3],[5,6]],[[4,5],[7,8]],[[35,72],[4,0]]])

In [113]:
print(s)
print(v)
print(m)
print(t)

tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor([3 4 5], shape=(3,), dtype=int32)
tf.Tensor(
[[ 3  4  9]
 [10 34  2]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[ 2  3]
  [ 5  6]]

 [[ 4  5]
  [ 7  8]]

 [[35 72]
  [ 4  0]]], shape=(3, 2, 2), dtype=int32)


Find the shape, rank and size of the tensors you created in 1.


In [114]:
print(tf.rank(s))
print(tf.rank(v))
print(tf.rank(m))
print(tf.rank(t))

print(tf.shape(s))
print(tf.shape(v))
print(tf.shape(m))
print(tf.shape(t))

print(tf.size(s))
print(tf.size(v))
print(tf.size(m))
print(tf.size(t))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([3], shape=(1,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor([3 2 2], shape=(3,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)


Create two tensors containing random values between 0 and 1 with shape [5, 300].


In [115]:
t1 = tf.constant(np.random.uniform(0, 1, size=1500))
t2 = tf.constant(np.random.uniform(0, 1, size=1500))

t1 = tf.reshape(t1, [5,300])
t2 = tf.reshape(t2, [5,300])

print(t1)
print(t2)

tf.Tensor(
[[0.4069949  0.53684251 0.14238215 ... 0.24977298 0.58546179 0.66002733]
 [0.00335124 0.13102531 0.08620931 ... 0.01789149 0.95399256 0.98389723]
 [0.86319407 0.94825555 0.11908623 ... 0.56181411 0.71115917 0.34793821]
 [0.42574811 0.34573557 0.60202567 ... 0.73167444 0.97633279 0.49281063]
 [0.27120611 0.53540606 0.20153139 ... 0.52251107 0.97807281 0.8861698 ]], shape=(5, 300), dtype=float64)
tf.Tensor(
[[0.29146413 0.20990932 0.20294974 ... 0.74078507 0.90201491 0.16173156]
 [0.55925669 0.05484863 0.30988971 ... 0.67623969 0.93489518 0.2827934 ]
 [0.51874127 0.54265112 0.60839857 ... 0.05049709 0.52528373 0.83648057]
 [0.90782793 0.13803958 0.06629649 ... 0.60391107 0.49748638 0.64829135]
 [0.98025053 0.4529264  0.01867876 ... 0.87755666 0.23167756 0.26741406]], shape=(5, 300), dtype=float64)


Multiply the two tensors you created in 3 using matrix multiplication.


In [116]:
tf.matmul(t1, tf.reshape(t2, [300, 5]))

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[74.64757753, 79.25756781, 74.53900912, 74.7743488 , 74.17727773],
       [79.75909003, 79.29288299, 75.83705478, 78.17796576, 75.96707758],
       [77.90406047, 85.67014147, 82.17699277, 78.06651406, 79.78776596],
       [77.73520857, 83.46157216, 75.39775854, 76.56051154, 79.90070889],
       [73.09389525, 83.2264154 , 74.90715515, 75.95254101, 78.59809838]])>

Multiply the two tensors you created in 3 using dot product.


In [117]:
tf.tensordot(t1, t2, axes=0)

<tf.Tensor: shape=(5, 300, 5, 300), dtype=float64, numpy=
array([[[[1.18624413e-01, 8.54320201e-02, 8.25995097e-02, ...,
          3.01495742e-01, 3.67115465e-01, 6.58239208e-02],
         [2.27614617e-01, 2.23231112e-02, 1.26123531e-01, ...,
          2.75226103e-01, 3.80497565e-01, 1.15095469e-01],
         [2.11125050e-01, 2.20856237e-01, 2.47615114e-01, ...,
          2.05520589e-02, 2.13787795e-01, 3.40443321e-01],
         [3.69481333e-01, 5.61814032e-02, 2.69823328e-02, ...,
          2.45788724e-01, 2.02474416e-01, 2.63851271e-01],
         [3.98956963e-01, 1.84338731e-01, 7.60215798e-03, ...,
          3.57161082e-01, 9.42915830e-02, 1.08836157e-01]],

        [[1.56470335e-01, 1.12688244e-01, 1.08952050e-01, ...,
          3.97684917e-01, 4.84239951e-01, 8.68243788e-02],
         [3.00232765e-01, 2.94450747e-02, 1.66361971e-01, ...,
          3.63034215e-01, 5.01891475e-01, 1.51815517e-01],
         [2.78482368e-01, 2.91318192e-01, 3.26614218e-01, ...,
          2.71089860e-0

Create a tensor with random values between 0 and 1 with shape [224, 224, 3].


In [118]:
t3 = tf.constant(np.random.uniform(0, 1, size=(224*224*3)))

t3 = tf.reshape(t3, [224,224,3])

t3

<tf.Tensor: shape=(224, 224, 3), dtype=float64, numpy=
array([[[0.33860866, 0.76751397, 0.47649729],
        [0.05276046, 0.89165039, 0.05936972],
        [0.91852992, 0.52026701, 0.99875695],
        ...,
        [0.66335249, 0.05634869, 0.30456826],
        [0.92075267, 0.78457769, 0.71677864],
        [0.30298054, 0.69069352, 0.09112368]],

       [[0.43436313, 0.72503526, 0.55665877],
        [0.72779296, 0.80755053, 0.35781926],
        [0.0569049 , 0.75585964, 0.52272987],
        ...,
        [0.52986911, 0.16633467, 0.1795951 ],
        [0.59404366, 0.48209264, 0.92210194],
        [0.73061808, 0.06593687, 0.67182706]],

       [[0.16847947, 0.57261303, 0.2999235 ],
        [0.35691859, 0.95645331, 0.85402319],
        [0.39333117, 0.47114745, 0.67164236],
        ...,
        [0.34223942, 0.11885593, 0.44595888],
        [0.66985282, 0.81171434, 0.92861354],
        [0.5168865 , 0.80278587, 0.02884437]],

       ...,

       [[0.59145048, 0.65049515, 0.30914135],
        [0.93

Find the min and max values of the tensor you created in 6 along the first axis.


In [120]:
tf.reduce_min(t3, axis=0)

<tf.Tensor: shape=(224, 3), dtype=float64, numpy=
array([[4.89708357e-04, 7.58617176e-06, 2.12716270e-03],
       [1.11942186e-03, 1.55023928e-02, 9.07325778e-06],
       [4.33117540e-04, 5.18672360e-03, 9.15782377e-04],
       [2.07514728e-03, 1.44803793e-03, 6.76357245e-03],
       [6.64364939e-03, 3.94495128e-03, 1.90062972e-03],
       [4.71815357e-03, 4.49586598e-03, 2.10073755e-03],
       [7.42607745e-03, 6.70882467e-03, 1.01286277e-03],
       [8.65545966e-03, 8.67872462e-05, 2.30400982e-03],
       [1.11601989e-02, 2.81606152e-02, 1.00656195e-02],
       [1.34358659e-03, 9.60090552e-04, 4.01331928e-03],
       [6.95352048e-03, 5.03847917e-04, 4.62376095e-04],
       [4.68539521e-04, 4.21808442e-03, 5.57394780e-03],
       [3.34467466e-03, 1.38447221e-03, 1.92517166e-03],
       [3.41944161e-04, 4.02002884e-03, 4.66754875e-03],
       [1.04442158e-03, 2.25123735e-03, 8.79051032e-03],
       [1.57851774e-03, 3.17644994e-03, 2.27312130e-03],
       [6.10752975e-03, 2.18570821e-03

Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].


In [123]:
t4 = tf.constant(np.random.uniform(0, 1, size=(224*224*3)))

t4 = tf.reshape(t4, [1,224,224,3])

t4

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float64, numpy=
array([[[[0.84707315, 0.67472123, 0.53998831],
         [0.00713127, 0.14934342, 0.32222015],
         [0.03669624, 0.21105728, 0.40607258],
         ...,
         [0.98769049, 0.59754636, 0.85270077],
         [0.90356277, 0.35295527, 0.9844377 ],
         [0.54279884, 0.66262427, 0.24759086]],

        [[0.80084436, 0.91648801, 0.73643194],
         [0.44622449, 0.10953846, 0.8691697 ],
         [0.2078697 , 0.90581855, 0.21092262],
         ...,
         [0.00336177, 0.09879137, 0.76299332],
         [0.72009028, 0.52350525, 0.94439538],
         [0.06954703, 0.36685526, 0.04794614]],

        [[0.40085888, 0.29727669, 0.82230264],
         [0.79033936, 0.17027979, 0.84904176],
         [0.51613769, 0.53156903, 0.63677309],
         ...,
         [0.23559194, 0.36665993, 0.68625788],
         [0.59992262, 0.26135936, 0.00238071],
         [0.78215418, 0.52163493, 0.24711236]],

        ...,

        [[0.79552347, 0.15002294, 

In [124]:
t4_squeezed = tf.squeeze(t4)
t4_squeezed

<tf.Tensor: shape=(224, 224, 3), dtype=float64, numpy=
array([[[0.84707315, 0.67472123, 0.53998831],
        [0.00713127, 0.14934342, 0.32222015],
        [0.03669624, 0.21105728, 0.40607258],
        ...,
        [0.98769049, 0.59754636, 0.85270077],
        [0.90356277, 0.35295527, 0.9844377 ],
        [0.54279884, 0.66262427, 0.24759086]],

       [[0.80084436, 0.91648801, 0.73643194],
        [0.44622449, 0.10953846, 0.8691697 ],
        [0.2078697 , 0.90581855, 0.21092262],
        ...,
        [0.00336177, 0.09879137, 0.76299332],
        [0.72009028, 0.52350525, 0.94439538],
        [0.06954703, 0.36685526, 0.04794614]],

       [[0.40085888, 0.29727669, 0.82230264],
        [0.79033936, 0.17027979, 0.84904176],
        [0.51613769, 0.53156903, 0.63677309],
        ...,
        [0.23559194, 0.36665993, 0.68625788],
        [0.59992262, 0.26135936, 0.00238071],
        [0.78215418, 0.52163493, 0.24711236]],

       ...,

       [[0.79552347, 0.15002294, 0.83939525],
        [0.11

Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.


In [127]:
t5 = tf.constant([1,2,3,4,4,6,7,3,2,7])
tf.reduce_max(t5)

<tf.Tensor: shape=(), dtype=int32, numpy=7>

One-hot encode the tensor you created in 9.

In [128]:
tf.one_hot(t5, depth=7)

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>